# MYSQL DATA
Host: "51.81.5.51"
Port: 3306
Database: "serverpro_db"
Username: "root"
Password: "0GlWRDr9jYOS05g"

# MineType
# Choices are Group (default), OnebyOne, All
# Group by group: There are 3 groups of tiers.
# OneByOne: You can do one tier at a time
# All: You can do all the tiers at once

MineType: OneByOne
TierList:

Tiers:
   
