--- 
api-version: 1.14
author: C10coding
commands: 
  blockbr: 
    aliases: 
      - bbr
    description: "Regular commands"
    permission: blockbr.use
depend: 
  - Vault
main: me.caleb.BlockBR.Main
name: BlockBR
permissions: 
  blockbr.admin: 
    default: op
    description: "Allows admin blockbr commands"
  blockbr.use: 
    default: true
    description: "Allows blockbr commands"
version: 2.1.1
