# MYSQL DATA. LEAVE THE DATABASE AS NONE. ADJUST ALL OTHER FIELDS
Host: ""
Port: 3306
Database: "none"
Username: ""
Password: ""

# MineType
# Choices are Group (default), OnebyOne, All
# Group by group: There are 3 groups of tiers.
# OneByOne: You can do one tier at a time
# All: You can do all the tiers at once

Side-Menu: true

MineType: OneByOne
TierList:
- grass
- oak_log
- stone
- coal
- iron
- redstone
- lapis
- gold
- obsidian
- diamond
- emerald

Tiers:
  grass:
    Properties:
      Material: GRASS_BLOCK
      Multiplier: 2.0
      MoneyMultiplier: 2.0
      Threshold: 500
      Rewards:
        Money: 0
        Crate: false
        Items: []
        Commands: []
  oak_log:
    Properties:
      Material: OAK_LOG
      Multiplier: 2.0
      MoneyMultiplier: 2.0
      Threshold: 500
      Rewards:
        Money: 0
        Crate: false
        Items: []
        Commands: []
  stone:
    Properties:
      Material: STONE
      Multiplier: 2.0
      MoneyMultiplier: 2.0
      Threshold: 500
      Rewards:
        Money: 0
        Crate: false
        Items: []
        Commands: []
  coal:
    Properties:
      Material: COAL_ORE
      Multiplier: 2.0
      MoneyMultiplier: 2.0
      Threshold: 500
      Rewards:
        Money: 0
        Crate: false
        Items: []
        Commands: []
  iron:
    Properties:
      Material: IRON_ORE
      Multiplier: 2.0
      MoneyMultiplier: 2.0
      Threshold: 500
      Rewards:
        Money: 0
        Crate: false
        Items: []
        Commands: []
  redstone:
    Properties:
      Material: REDSTONE_ORE
      Multiplier: 2.0
      MoneyMultiplier: 2.0
      Threshold: 500
      Rewards:
        Money: 0
        Crate: false
        Items: []
        Commands: []
  lapis:
    Properties:
      Material: LAPIS_ORE
      Multiplier: 2.0
      MoneyMultiplier: 2.0
      Threshold: 500
      Rewards:
        Money: 0
        Crate: false
        Items: []
        Commands: []
  gold:
    Properties:
      Material: GOLD_ORE
      Multiplier: 2.0
      MoneyMultiplier: 2.0
      Threshold: 500
      Rewards:
        Money: 0
        Crate: false
        Items: []
        Commands: []
  obsidian:
    Properties:
      Material: OBSIDIAN
      Multiplier: 2.0
      MoneyMultiplier: 2.0
      Threshold: 500
      Rewards:
        Money: 0
        Crate: false
        Items: []
        Commands: []
  diamond:
    Properties:
      Material: DIAMOND_ORE
      Multiplier: 2.0
      MoneyMultiplier: 2.0
      Threshold: 500
      Rewards:
        Money: 0
        Crate: false
        Items: []
        Commands: []
  emerald:
    Properties:
      Material: EMERALD_ORE
      Multiplier: 2.0
      MoneyMultiplier: 2.0
      Threshold: 500
      Rewards:
        Money: 0
        Crate: false
        Items: []
        Commands: []
   
Help:
- '/&6bbr tierlist: &rShows you all the tiers'
- '/&6bbr menu &rBrings up the BlockBR menu'
- '/&6bbr tier add (Tier Name): &rCreates a new tier'
- '/&6bbr tier remove (Tier name): &rRemoves the desired tier'
- '/&6bbr tier remove all: &rRemoves all tiers'
- '/&6bbr tier edit ("mult" | "mat" | "thresh") (Your multiplier | Your material/Item name | Your threshold number): &rEdits a specific property of a tier. (Multiplier, Material, Threshold)'
- '/&6bbr tier rename (tier name) (new tier name):&r Renames the desired tier'
- '/&6bbr rewardadd (The tier) ("item"):&r Adds the item in your hand to the rewards list for this tier'
- '/&6bbr rewardadd (The tier) ("command"):&r Asks what command you would like to add to this tier'

Help2:
- '/&6bbr rewardedit (The tier) ("money") (The amount): &rEdits the money amount for this tier'
- '/&6bbr rewardedit (The tier) ("crate") (The crate): &rAdds the desired crate you want for this tier'
- '/&6bbr rewardremove (The tier) ("item") (# Item): &rRemoves the desired reward item from the tier'
- '/&6bbr rewardremove (The tier) ("command") (# Command): &rRemoves the desired reward item from the tier'
- '/&6bbr changeType ("all" | "group" | "onebyone"):&r Changes the mine type'
- '/&6bbr group create (Group name):&r Creates a new group'
- '/&6bbr group remove (Group name):&r Removes the desired group'
- '/&6bbr tier move (Tier name) (Group name):&r Moves the desired tier to the desired group'

Help3:
- '/&6bbr groupList:&r Shows you all the groups'
- '/&6bbr group tierList (Group name):&r Shows you tiers within a desired group'
- '/&6bbr group rename (Group) (New Group name): &rRenames the desired group'
- '/&6bbr help: &rBrings up this'