name: BlockBR_2.0
version: 2.0
main: me.caleb.BlockBR.Main
author: Caleb Owens
api-version: 1.13

commands:
  blockbr:
    description: Regular commands
    permission: blockbr.use
    aliases: [bbr]
permissions:
  blockbr.use:
    description: Allows blockbr commands
    default: true
  blockbr.admin:
    description: Gives all blockbr commands, including the admin ones
    default: op
    children:
      blockbr.use
    